included:
  - ../AppAssistant
  - AppAssistant/Classes

excluded:
  - Pods

analyzer_rules:
  - unused_declaration
  - unused_import

disabled_rules: # 执行时排除掉的规则
  - switch_case_alignment

force_cast: warning # 隐式
force_try:
  severity: warning # 显式
# 同时有警告和错误等级的规则，可以只设置它的警告等级
# 隐式
line_length: 160
# they can set both implicitly with an array
type_body_length:
  - 400 # warning
  - 800 # error

function_body_length:
  - 80 # warning
  - 120 # error

# 或者也可以同时进行显式设置
file_length:
  warning: 600
  error: 2000

identifier_name:
  min_length: # 只有最小长度
    error: 3 # 只有错误
  excluded: # 排除某些名字
    - id
    - url
    - vc
    - ip
    - x
    - y
    - z

reporter: "xcode" # 报告类型 (xcode, json, csv, checkstyle, junit, html, emoji)

opt_in_rules:

  - implicitly_unwrapped_optional
  - conditional_returns_on_newline
  - force_unwrapping
  # - function_default_parameter_at_end
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - discouraged_object_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - extension_access_modifier
  - fallthrough
#  - fatal_error_message
#  - file_header
#  - file_name
  - first_where
  - identical_operands
  - joined_default_parameter
  - legacy_random
  - let_var_whitespace
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
#  - number_separator
#  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
#  - unavailable_function
#  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  # - vertical_whitespace_closing_braces
  - xct_specific_matcher
  - yoda_condition
